### ISSUE TITLE
An error for install requirements.txt

### ISSUE THREAD

**Issue by le0820** [felipemaiapolo/tinyBenchmarks#1]
I followed the tutorials to clone the repo, but I got an error when installing requirements.txt.
`
cd tinyBenchmarks/tutorials/
pip install -r requirements.txt
ERROR: /home/skunk/tutorials/py-irt is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
`

**Comment by felipemaiapolo** [comment]
Hello,

Thank you for raising this issue. I have updated the requirements.txt. Please try it again and let me know!

**Comment by le0820** [comment]
It's fine! Thank you.
