### ISSUE TITLE
Release of benchmarks data

### ISSUE THREAD

**Issue by petroskarypis** [felipemaiapolo/tinyBenchmarks#4]
Hi, thanks for making this interesting work open-source! Are you guys planning to release the collection of model benchmarks described in Appendix C?

**Comment by LucWeber** [comment]
Hey,

the benchmarks in Appendix C are publically available benchmarks (see [open LLM leaderboard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard) and [HELM](https://crfm.stanford.edu/helm/lite/latest/)).

If you are looking for the tinyBenchmarks, you can find them on [here](https://huggingface.co/tinyBenchmarks).

Hope this helps!

**Comment by petroskarypis** [comment]
Hey, thanks for the reply! 

I was referring to those benchmarks in Appendix C. While you describe the preprocessing steps you used, having your version of them would be useful for reproducibility. For example HELM Lite currently only lists 30 models vs. the 37 mentioned in the appendix.

**Comment by felipemaiapolo** [comment]
Hi @petroskarypis,

Now we understand what you mean. We will release the datasets as soon as possible in our GitHub repo. If you want I can send you via email in the meantime. Just email felipemaiapolo@gmail.com and I will reply with the datasets.

**Comment by petroskarypis** [comment]
Thanks! That would be great.
