### ISSUE TITLE
Is there a tiny benchmark for Hendryck's MATH dataset? 

### ISSUE THREAD

**Issue by brando90** [felipemaiapolo/tinyBenchmarks#7]
or this is my best bet? https://github.com/felipemaiapolo/tinyBenchmarks/tree/main/tutorials create my own

**Comment by felipemaiapolo** [comment]
Hi Brando,

I hope you are doing well. We have not created a tiny dataset for Hendryck's MATH. However, please let us know if you need any help doing it.

Best,
Felipe
