### ISSUE TITLE
The correspondence between the predictions data and model

### ISSUE THREAD

**Issue by marvelcell** [felipemaiapolo/tinyBenchmarks#8]
Thank you for your outstanding work, it really helps me a lot!

I notice that you've released the predictions data of the models you mentioned in paper, but I can't find the corresponding relationship between the data and the model, and I don't know which prediction data comes from which model.
Could you please explain that?

Thank you very much, and thank you for your excellent work again!

**Comment by LucWeber** [comment]
Hey Zhang Yueqi,

happy to hear that it is helpful!
In the pickle files, the ordering of the list of models (under the 'model' key) corresponds to the ordering of model dimension in the correctness data. 
Let me know if that resolves your question.

Best,
Lucas

**Comment by marvelcell** [comment]
Thank you for your fast reply, Your answer solved my problem！
