### ISSUE TITLE
How does this compare with MixEval?

### ISSUE THREAD

**Issue by ogencoglu** [felipemaiapolo/tinyBenchmarks#9]
https://mixeval.github.io/

**Comment by felipemaiapolo** [comment]
Hello,

Mix-eval is a novel benchmark built on top of existing benchmarks. On the other hand, tinyBenchmarks comprises "tiny" versions of existing benchmarks. We do not propose a different benchmark. Does that make sense?

**Comment by ogencoglu** [comment]
Thanks for your swift reply. Understood.

Do you have any correlation with lmsys Chatbot Arena (not that it is the most important metric anyway but out of curiosity)?

**Comment by felipemaiapolo** [comment]
I think the mix-eval paper reports these correlations for the datasets we work with.
